package docs:getcoordsfromaddressworld@0.1.0;

interface getcoordsfromaddress {
	record address {
		street: string,
		streetnumber: string,
		zip: string,
		town: string,
		region: option<string>,
		count: option<u32>,
	}

	record coordinates {
		longitude: f64,
		latitude: f64,
	}

	getcoordsfromaddress: func(address: address) -> coordinates;
}

world getcoordsfromaddressworld {
    import wasi:cli/environment@0.2.0;
    import wasi:http/outgoing-handler@0.2.0;
    import wasi:http/types@0.2.0;
    import wasi:io/poll@0.2.0;
    import wasi:io/streams@0.2.0;
    import wasi:io/error@0.2.0;
    import wasi:clocks/monotonic-clock@0.2.0;

    export getcoordsfromaddress;
}
